src/main/java/br/com/sigedepri/entity/transacao/FiltroTransacao.java
package br.com.sigedepri.entity.transacao;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import br.com.sigedepri.entity.Categoria;
import br.com.sigedepri.enuns.TipoConsulta;
import br.com.sigedepri.enuns.TipoTransacao;

public class FiltroTransacao implements Serializable {
	
	private static final long serialVersionUID = 1L;
	public static final String TRANSACAO_FILTER = "transacaoFilter"; 

	private String descricao;
	private TipoTransacao tipoTransacao;
	private Categoria categoria;
	private Categoria subCategoria;
	private TipoConsulta tipoData;
	private Date dataInicial;
	private Date dataFinal;
	private TipoConsulta tipoValor;
	private BigDecimal valorInicial;
	private BigDecimal valorFinal;
	
	public FiltroTransacao() {
	}
	
	public FiltroTransacao(Date dataInical, Date dataFinal) {
		this.dataInicial = dataInical;
		this.dataFinal = dataFinal;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public TipoTransacao getTipoTransacao() {
		return tipoTransacao;
	}

	public void setTipoTransacao(TipoTransacao tipoTransacao) {
		this.tipoTransacao = tipoTransacao;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public Categoria getSubCategoria() {
		return subCategoria;
	}

	public void setSubCategoria(Categoria subCategoria) {
		this.subCategoria = subCategoria;
	}

	public TipoConsulta getTipoData() {
		return tipoData;
	}

	public void setTipoData(TipoConsulta tipoData) {
		this.tipoData = tipoData;
	}

	public Date getDataInicial() {
		return dataInicial;
	}

	public void setDataInicial(Date dataInicial) {
		this.dataInicial = dataInicial;
	}

	public Date getDataFinal() {
		return dataFinal;
	}

	public void setDataFinal(Date dataFinal) {
		this.dataFinal = dataFinal;
	}

	public TipoConsulta getTipoValor() {
		return tipoValor;
	}

	public void setTipoValor(TipoConsulta tipoValor) {
		this.tipoValor = tipoValor;
	}

	public BigDecimal getValorInicial() {
		return valorInicial;
	}

	public void setValorInicial(BigDecimal valorInicial) {
		this.valorInicial = valorInicial;
	}

	public BigDecimal getValorFinal() {
		return valorFinal;
	}

	public void setValorFinal(BigDecimal valorFinal) {
		this.valorFinal = valorFinal;
	}
}

src/main/java/br/com/sigedepri/entity/transacao/Transacao.java
package br.com.sigedepri.entity.transacao;

import java.math.BigDecimal;
import java.text.NumberFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

import br.com.sigedepri.entity.AbstractEntity;
import br.com.sigedepri.entity.Categoria;
import br.com.sigedepri.entity.Usuario;
import br.com.sigedepri.enuns.TipoTransacao;
import br.com.sigedepri.util.Formatador;

	
@Entity
@Table(name = "TRANSACAO")
public class Transacao extends AbstractEntity<Integer> {

	private static final long serialVersionUID = 1L;

	public static final String SEQUENCE_NAME = "SEQ_TRANSACAO";

	@Id
	@SequenceGenerator(name = SEQUENCE_NAME, sequenceName = SEQUENCE_NAME, initialValue = 1, allocationSize = 1)
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = SEQUENCE_NAME)
	@Column(unique = true, nullable = false, precision = 8, name = "ID_TRANSACAO")
	private Integer id;

	@NotBlank
	private String descricao;

	@NotNull
	@Temporal(value=TemporalType.TIMESTAMP)
	private Date dataTransacao;

	@NotNull
	private BigDecimal valor;

	@NotNull
	@Enumerated(EnumType.STRING)
	private TipoTransacao tipo;

	@ManyToOne
	@JoinColumn(name = "CATEGORIA_ID")
	private Categoria categoria;
	
	@ManyToOne
	@JoinColumn(name= "USUARIO_ID")
	private Usuario usuario;
	
	@Column(name = "idOFX")
	private String idOFX;
	
	@Transient
	private boolean selecionado;
	
	@Transient
	private Categoria categoriaPai;
	
	@Transient
	private List<Categoria> subCategorias;
	
	@Transient
	private boolean editando;
	
	public Transacao() {
	}

	public Transacao(String descricao, Date dataTransacao, BigDecimal valor) {
		super();
		this.descricao = descricao;
		this.dataTransacao = dataTransacao;
		this.valor = valor;
	}
	
	public Transacao(String idOFX, BigDecimal valor, Date dataTransacao, String descricao, TipoTransacao tipo) {
		super();
		this.descricao = descricao;
		this.dataTransacao = dataTransacao;
		this.valor = valor;
		this.idOFX = idOFX;
		this.tipo = tipo;
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescricao() {
		return descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	public Date getDataTransacao() {
		return dataTransacao;
	}
	
	public String getDataTransacaoFormatada(){
		return Formatador.convertDateToStringSemHora(getDataTransacao());
	}

	public void setDataTransacao(Date dataTransacao) {
		this.dataTransacao = dataTransacao;
	}

	public BigDecimal getValor() {
		return valor;
	}
	
	public String getValorFormatado() {
		Locale ptBR = new Locale("pt", "BR");
		NumberFormat moedaFormat = NumberFormat.getCurrencyInstance(ptBR);
		return moedaFormat.format(getValor());
	}

	public void setValor(BigDecimal valor) {
		this.valor = valor;
	}

	public TipoTransacao getTipo() {
		return tipo;
	}

	public void setTipo(TipoTransacao tipo) {
		this.tipo = tipo;
	}

	public Categoria getCategoria() {
		return categoria;
	}

	public void setCategoria(Categoria categoria) {
		this.categoria = categoria;
	}

	public boolean isSelecionado() {
		return selecionado;
	}

	public void setSelecionado(boolean selecionado) {
		this.selecionado = selecionado;
	}

	public Categoria getCategoriaPai() {
		return categoriaPai;
	}

	public void setCategoriaPai(Categoria categoriaPai) {
		this.categoriaPai = categoriaPai;
	}

	public List<Categoria> getSubCategorias() {
		return subCategorias;
	}

	public void setSubCategorias(List<Categoria> subCategorias) {
		this.subCategorias = subCategorias;
	}
	
	public boolean isEditando(){
		//return getId() == null && editando;
		return editando;
	}

	public Usuario getUsuario() {
		return usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public String getIdOFX() {
		return idOFX;
	}

	public void setIdOFX(String idOFX) {
		this.idOFX = idOFX;
	}

	public void setEditando( boolean editando ) {
		this.editando = editando;
	}

}

src/main/java/br/com/sigedepri/controllers/transacao/CadastroTransacaoEmLoteBean.java
package br.com.sigedepri.controllers.transacao;

import java.io.IOException;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.view.ViewScoped;
import javax.inject.Inject;
import javax.inject.Named;

import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.UploadedFile;

import br.com.sigedepri.controllers.AbstractBean;
import br.com.sigedepri.dao.TransacaoDAO;
import br.com.sigedepri.entity.Categoria;
import br.com.sigedepri.entity.transacao.Transacao;
import br.com.sigedepri.service.CategoriaService;
import br.com.sigedepri.service.TransacaoService;
import br.com.sigedepri.util.Formatador;
import br.com.sigedepri.util.excpetion.CoreException;
import br.com.sigedepri.util.excpetion.ServiceException;
import br.com.sigedepri.util.jsf.FacesUtil;

@Named
@ViewScoped
public class CadastroTransacaoEmLoteBean extends AbstractBean<Integer, Transacao, TransacaoDAO, TransacaoService> {

	private static final long serialVersionUID = 1L;
	
	@Inject
	private CategoriaService categoriaService;
	
	private List<Categoria> categoriasPai;
	private List<Categoria> subCategorias;
	private Categoria categoriaPaiSelecionada;
	
	private boolean selecionaTodos;
	
	private List<Transacao> transacoesEmLote;
	private Transacao transacaoSelecionada;

	private UploadedFile arquivoCarregado; 
	
	@PostConstruct
	public void init(){
		System.out.println("Iniciando cadastro transação em lote");
	}
	
	public void handleFileUpload(FileUploadEvent event) {
		try {
			this.arquivoCarregado = event.getFile();
			this.transacoesEmLote = getService().carregarArquivoEmLote(event.getFile().getInputstream());
		} catch (IOException | ServiceException e) { 
			e.printStackTrace();
			FacesUtil.addErrorMessage("Não foi possível carregar o arquivo " + event.getFile().getFileName()); 
		} 
    }
	
	public String calculaValorTotal(){
		BigDecimal total = BigDecimal.ZERO;
		if(transacoesEmLote != null && transacoesEmLote.size() > 0){
			for (Transacao transacao : transacoesEmLote) {
				total = total.add(transacao.getValor());
			}
		}
		return Formatador.formataNumero(total);
	}
	
	public void salvarPorLinha(Transacao transacaoAtual) throws CoreException {
		try {
			int indexOf = getTransacoesEmLote().indexOf(transacaoAtual);
			transacaoAtual = getService().salva(transacaoAtual);
			getTransacoesEmLote().set(indexOf, transacaoAtual);
			FacesUtil.addInfoMessage("Registro salvo com sucesso!");
		} catch (ServiceException e) {
			throw new CoreException(e.getCause().getMessage());
		} catch (Exception e) {
			throw new CoreException("Não foi possível salvar a transação " + transacaoAtual.getDescricao());
		}
	}
	
	public void selecionarTodos(){
		if(this.getTransacoesEmLote() != null && !this.getTransacoesEmLote().isEmpty()){
			for (Transacao transacao : this.getTransacoesEmLote()) {
				if(selecionaTodos){
					transacao.setSelecionado(true);
				}else {
					transacao.setSelecionado(false);
				}
			}
		}
	}

	public void onChangeCategoriaPai(Transacao transacaoAtual){
		transacaoAtual.setSubCategorias(this.categoriaService.listaSubCategorias(transacaoAtual.getCategoriaPai()));
	}

	public List<Categoria> getCategoriasPai() {
		if(categoriasPai == null){
			this.categoriasPai = categoriaService.listaCategoriasPai();
		}
		return categoriasPai;
	}

	public List<Categoria> getSubCategorias() {
		return subCategorias;
	}

	public Categoria getCategoriaPaiSelecionada() {
		return categoriaPaiSelecionada;
	}

	public void setCategoriaPaiSelecionada(Categoria categoriaPaiSelecionada) {
		this.categoriaPaiSelecionada = categoriaPaiSelecionada;
	}

	public void setSubCategorias(List<Categoria> subCategorias) {
		this.subCategorias = subCategorias;
	}

	public List<Transacao> getTransacoesEmLote() {
		return transacoesEmLote;
	}

	public void setTransacoesEmLote(List<Transacao> transacoesEmLote) {
		this.transacoesEmLote = transacoesEmLote;
	}

	public boolean isSelecionaTodos() {
		return selecionaTodos;
	}

	public void setSelecionaTodos(boolean selecionaTodos) {
		this.selecionaTodos = selecionaTodos;
	}

	public Transacao getTransacaoSelecionada() {
		return transacaoSelecionada;
	}

	public void setTransacaoSelecionada(Transacao transacaoSelecionada) {
		this.transacaoSelecionada = transacaoSelecionada;
	}

	public UploadedFile getArquivoCarregado() {
		return arquivoCarregado;
	}

	public void setArquivoCarregado(UploadedFile arquivoCarregado) {
		this.arquivoCarregado = arquivoCarregado;
	}
	
	public void removeTodosSelecionados(){
		List<Transacao> transacaoToRemove = new ArrayList<>();
		for ( Transacao transacao : getTransacoesEmLote() ) {
			if( transacao.isSelecionado() ){
				transacaoToRemove.add( transacao ); 
			}
		}
		getTransacoesEmLote().removeAll( transacaoToRemove ); 
	}
	
	public void editar(Transacao transacao){
		transacao.setEditando( true ); 
	}

}

src/main/webapp/transacao/cadastroTransacao.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/template/template.xhtml"> 

	<ui:define name="content">
		<div class="Container100">
			<div class="ContainerIndent">
				<div class="Card ShadowEffect">
				<h3>Nova Transação</h3>
				<div class="SeparatorFull"></div>   
							
				<h:form id="frmPesquisa" prependId="false"> 
						
					<p:messages id="msglocal" autoUpdate="true" closable="true" escape="2"/> 
		                		
		            <div class="ui-fluid">	
			        	<div class="ui-g-12 ui-md-9 ui-lg-8">
				        	<p:outputLabel value="Descrição" for="descrição"/>       
				        	<p:inputText id="descrição" value="#{cadastroTransacao.transacao.descricao}"/>
			        	</div>
		              		
	              		<div class="ui-g-12 ui-md-3 ui-lg-4">
		              		<p:outputLabel value="Tipo" for="tipo"/>       
				        	<p:selectOneButton id="tipo" value="#{cadastroTransacao.transacao.tipo}">
				        		<f:selectItems value="#{enunsComplete.tipoTransacao()}" var="_tipo" itemLabel="#{_tipo.descricao}" itemValue="#{_tipo}"/>
				        	</p:selectOneButton>
			        	</div>
			        	
			        	
			        	<div class="ui-g-12 ui-md-6 ui-lg-3">
				        	<p:outputLabel value="Categoria"/>
		            		<p:selectOneMenu id="categoria" value="#{cadastroTransacao.transacao.categoriaPai}" filter="true" filterMatchMode="startsWith" converter="#{abstractConverter}">
				            	<f:selectItem itemLabel="Selecione" itemValue="#{null}" /> 
				            	<f:selectItems value="#{cadastroTransacao.categoriasPai}" var="_pai" itemLabel="#{_pai.nome}" itemValue="#{_pai}"/>
				        		<p:ajax event="change" process="@this" update="subcategoria" partialSubmit="true" listener="#{cadastroTransacao.onChangeCategoriaPai()}"/>
				        	</p:selectOneMenu> 
			        	</div>
		              			
				        <div class="ui-g-12 ui-md-6 ui-lg-3">
				        	<p:outputLabel value="Sub Categoria"/>
		            		<p:selectOneMenu id="subcategoria" value="#{cadastroTransacao.transacao.categoria}" filter="true" filterMatchMode="startsWith" converter="#{abstractConverter}">
				            	<f:selectItem itemLabel="Select One" itemValue="" /> 
				            	<f:selectItems value="#{cadastroTransacao.subCategorias}" var="_sub" itemLabel="#{_sub.nome}" itemValue="#{_sub}"/>
				        	</p:selectOneMenu>
				        </div>	
				        	
						<div class="ui-g-12 ui-md-6 ui-lg-3">
						 	<p:outputLabel value="Data" for="data">
		            			<p:calendar id="data" value="#{cadastroTransacao.transacao.dataTransacao}" pattern="dd-MM-yyyy" mask="true"/> 	
						 	</p:outputLabel>       
						</div>
						
						<div class="ui-g-12 ui-md-6 ui-lg-3">
		            		<p:outputLabel value="Valor">
			            		<p:inputText id="currency" value="#{cadastroTransacao.transacao.valor}"/>
		            		</p:outputLabel>
						</div> 	
		            	
		            	<div class="EmptyBox10"/>
		           			
		            </div> 
		            
			        <div class="EmptyBox20"/>  
			               		
					<div class="ui-g">
						<div class="ui-g-12">  
							<p:commandButton value="Salvar" icon="fa fa-floppy-o" title="Salvar" action="#{cadastroTransacao.salvar()}" update="@form msglocal"/>
							<p:button styleClass="RedButton" icon="fa fa-reply" value="Voltar" title="Voltar para pesquisa" process="@this" outcome="/transacao/pesquisaTransacao"/>
						</div> 
					</div>
							
				</h:form>
				</div> 
			</div>
		</div>  
		
		<script>
		  $(function() {
		    $('#currency').maskMoney();
		  })
		</script>
		
	</ui:define>
</ui:composition>

src/main/webapp/transacao/cadastroTransacaoEmLote.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/WEB-INF/template/template.xhtml">

	<ui:define name="content">

		<h:form id="frmCadastroLote" enctype="multipart/form-data" acceptcharset="ISO-8859-1" prependId="false" >
		<div class="Container100">
			<div class="ContainerIndent">
				<div class="Card ShadowEffect">
					<h3>Transação em Lote</h3>
					<div class="SeparatorFull"></div> 
						
					<div class="EmptyBox10"/>
					
					<div class="Container100">
						<div class="Container50">
							<p:fileUpload fileUploadListener="#{cadastroTransacaoEmLoteBean.handleFileUpload}" mode="advanced" dragDropSupport="false" uploadLabel="Carregar documento(s)"
                  				  label="Adicionar Documento(s)" invalidFileMessage="Formato do arquivo inválido, informe um arquivo com extensão .csv" allowTypes="/(\.|\/)(ofx)$/" cancelLabel="Cancelar" multiple="false" update="@form" fileLimit="1" process="@this"/>     
						</div>  
						<div class="Container50 TexAlRight" style="margin-top: 5px;">    
							<p:commandButton value="Limpar Tudo" styleClass="OrangeButton"/> 
						</div> 
					</div> 
					
					<div class="EmptyBox10"/> 
				</div>
			</div>
		</div>
		
		<div class="Container100">
			<div class="ContainerIndent">
				<div class="Card ShadowEffect">
						<h2 class="CardTopic">
							<i class="icon-tack Fs18 Fleft MarRight10"></i> LISTA DE TRANSAÇÕES
								<p:commandButton id="imenutransaction" type="button" icon="fa fa-ellipsis-v Gray Fs20" styleClass="Fright GrayButton TransactionButton" style="margin-top:-10px !important;" />
								<p:menu overlay="true" trigger="imenutransaction" my="left top"	at="left bottom">
									<p:menuitem value="Nova transação +" icon="ui-icon-disk fa fa-square-o" outcome="/transacao/cadastroTransacao" />
									<p:menuitem value="Excluir selecionado(s)" icon="ui-icon-disk fa fa-close" disabled="#{empty cadastroTransacaoEmLoteBean.transacoesEmLote}" action="#{cadastroTransacaoEmLoteBean.removeTodosSelecionados()}" update="iteste ipanelfooter" process="@this" partialSubmit="true"/>
								</p:menu>
						</h2>
						
						<div class="SeparatorFull"></div> 
						
						<p:sticky target="ipanelheader" margin="68" /> 
										
						<p:panelGrid id="ipanelheader" columns="8" columnClasses="Wid2,Wid33,Wid10,Wid15,Wid18,Wid8,Wid6"  layout="grid" styleClass="ui-panelgrid-blank" style="border:0px none;padding-left: 10px;background-color: white;">
							<p:selectBooleanCheckbox value="#{cadastroTransacaoEmLoteBean.selecionaTodos}" title="Selecionar todos">
								<p:ajax event="change" update="iteste" process="@this" partialSubmit="true" listener="#{cadastroTransacaoEmLoteBean.selecionarTodos()}"/>
							</p:selectBooleanCheckbox>
							<h:outputText value="Descrição" styleClass="Fs14 Whitee FontBold" /> 
							<h:outputText value="Data" styleClass="Fs14 Whitee FontBold" /> 
							<h:outputText value="Categoria" styleClass="Fs14 Whitee FontBold" />
							<h:outputText value="Sub Categoria" styleClass="Fs14 Whitee FontBold" />
							<h:outputText value="Valor" styleClass="Fs14 Whitee FontBold"/> 
							<h:outputText value="" styleClass="Fs14 Whitee FontBold"/> 
						</p:panelGrid> 
						
										
						<div class="SeparatorFull"></div>     
									
						<p:dataGrid emptyMessage="Nehum arquivo adicionado" id="iteste" rowIndexVar="_row" var="_transacao" value="#{cadastroTransacaoEmLoteBean.transacoesEmLote}" layout="grid" columns="1" style="border: 0px !important;" >

							<p:panelGrid id="ipanelgridtransacoes" columns="8" columnClasses="Wid2,Wid33,Wid10,Wid15,Wid18,Wid8,Wid6"  layout="grid" styleClass="ui-panelgrid-blank" style="border:0px none;">

								<p:selectBooleanCheckbox value="#{_transacao.selecionado}">
									<p:ajax event="change" update="iteste" process="@this" partialSubmit="true" immediate="true" />  
								</p:selectBooleanCheckbox>    
								
								<p:inputText value="#{_transacao.descricao}" styleClass="Wid90" rendered="#{_transacao.editando}"/> 
								<p:outputLabel value="#{_transacao.descricao}" styleClass="Wid90 Fs14" rendered="#{!_transacao.editando}"/> 
								
								<p:calendar pattern="dd/MM/yyyy" value="#{_transacao.dataTransacao}" size="10" rendered="#{_transacao.editando}"/>
								<p:outputLabel value="#{_transacao.dataTransacaoFormatada}" styleClass="Wid90 Fs14" rendered="#{!_transacao.editando}"/> 
								
								<p:selectOneMenu value="#{_transacao.categoriaPai}" required="true" converter="#{abstractConverter}" height="190" rendered="#{_transacao.editando}" >
									<f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
									<f:selectItems value="#{cadastroTransacaoEmLoteBean.categoriasPai}" var="_pai" itemLabel="#{_pai.nome}" itemValue="#{_pai}"/>
									<p:ajax event="change" update="iteste:#{_row}:ionemenusub" process="@this" partialSubmit="true" listener="#{cadastroTransacaoEmLoteBean.onChangeCategoriaPai(_transacao)}"/>
								</p:selectOneMenu>
								<p:outputLabel value="#{_transacao.categoria.categoriaPai.nome}" styleClass="Wid90 Fs14" rendered="#{!_transacao.editando}"/>
								
								<p:selectOneMenu id="ionemenusub" required="true" value="#{_transacao.categoria}" converter="#{abstractConverter}" height="190" rendered="#{_transacao.editando}" >
									<f:selectItem itemLabel="Selecione" itemValue="#{null}"/>
									<f:selectItems value="#{_transacao.subCategorias}" var="_sub" itemLabel="#{_sub.nome}" itemValue="#{_sub}"/>
								</p:selectOneMenu>
								<p:outputLabel value="#{_transacao.categoria.nome}" styleClass="Wid90 Fs14" rendered="#{!_transacao.editando}"/>
								
								<p:inputNumber value="#{_transacao.valor}" rendered="#{_transacao.editando}" symbol=" R$ " decimalPlaces="2" size="11" emptyValue="0.00" decimalSeparator="," thousandSeparator=".">
						        	<f:converter converterId="javax.faces.BigDecimal" /> 
						        </p:inputNumber>
						        <p:outputLabel value="#{_transacao.valorFormatado}" styleClass="Wid90 Fs14" rendered="#{!_transacao.editando}"/>
						        
						        <h:panelGroup layout="block" style="margin-top: 10px;">
						        	
						        	<p:commandLink id="ibtnSalvar" rendered="#{_transacao.editando}" title="Salvar" update="iteste:#{_row}:ipanelgridtransacoes" process="@this iteste:#{_row}:ipanelgridtransacoes" action="#{cadastroTransacaoEmLoteBean.salvarPorLinha(_transacao)}">  
										<i class="fa fa-check Fs18"></i>  
		            				</p:commandLink>
						        
									<p:commandLink id="ibtnEditar" rendered="#{!_transacao.editando}" title="Editar" action="#{cadastroTransacaoEmLoteBean.editar(_transacao)}" update="iteste:#{_row}:ipanelgridtransacoes" process="@this iteste:#{_row}:ipanelgridtransacoes">  
										<i class="fa fa-pencil-square-o Fs18"></i>  
		            				</p:commandLink>
		            				
		            				<p:commandLink id="ibtnExcluir" update="iteste ipanelfooter" immediate="true" title="Excluir" style="padding-left: 10px;">
										<i class="fa fa-trash-o Fs18 Red"></i>  
										<p:collector unique="true" value="#{_transacao}" removeFrom="#{cadastroTransacaoEmLoteBean.transacoesEmLote}"/>
	                				</p:commandLink> 
                				</h:panelGroup>
                				
							</p:panelGrid>  

							<div class="SeparatorFull"></div> 
										
						</p:dataGrid>
						
						<p:panelGrid id="ipanelfooter" columns="8" columnClasses="Wid2,Wid33,Wid10,Wid15,Wid15 TexAlCenter,Wid10,Wid6"  layout="grid" styleClass="ui-panelgrid-blank" style="border:0px none;padding-left: 10px;">
							<h:outputLabel styleClass="Fs16 FontBold" /> 
							<h:outputLabel styleClass="Fs16 FontBold" /> 
							<h:outputLabel styleClass="Fs16 FontBold" /> 
							<h:outputLabel styleClass="Fs16 FontBold" />
							<h:outputText value="Total:" styleClass="Fs16 FontBold" />
							<h:outputText value="#{cadastroTransacaoEmLoteBean.calculaValorTotal()}" styleClass="Fs16 Orange FontBold"/> 
							<h:outputText value="" styleClass="Fs16 Whitee FontBold"/> 
						</p:panelGrid>
						
					</div>
				</div>
			</div>
		</h:form> 
		<script>
		  $(function() {
		    $('#currency').maskMoney();
		  })
		</script>
		
	</ui:define>
</ui:composition>